
-- Enable RLS
alter default privileges in schema public grant all on tables to postgres, anon, service_role;

-- Campaigns
CREATE TABLE IF NOT EXISTS campaigns (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  subtitle TEXT,
  year TEXT,
  scope TEXT,
  activation_dates TEXT,
  overview TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

ALTER TABLE campaigns ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read access for campaigns" ON campaigns FOR SELECT USING (true);
CREATE POLICY "Public insert access for campaigns" ON campaigns FOR INSERT WITH CHECK (true);
CREATE POLICY "Public update access for campaigns" ON campaigns FOR UPDATE USING (true);


-- Platforms
CREATE TABLE IF NOT EXISTS platforms (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  type TEXT,
  is_new BOOLEAN DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

ALTER TABLE platforms ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read access for platforms" ON platforms FOR SELECT USING (true);
CREATE POLICY "Public insert access for platforms" ON platforms FOR INSERT WITH CHECK (true);
CREATE POLICY "Public update access for platforms" ON platforms FOR UPDATE USING (true);


-- Touchpoints
CREATE TABLE IF NOT EXISTS touchpoints (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  platform TEXT NOT NULL,
  description TEXT,
  is_new BOOLEAN DEFAULT false,
  is_optional BOOLEAN DEFAULT false,
  tier_premium BOOLEAN DEFAULT false,
  tier_executive BOOLEAN DEFAULT false,
  sort_order INTEGER,
  image_url TEXT,
  marker_positions JSONB DEFAULT '[]'::jsonb,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

ALTER TABLE touchpoints ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read access for touchpoints" ON touchpoints FOR SELECT USING (true);
CREATE POLICY "Public insert access for touchpoints" ON touchpoints FOR INSERT WITH CHECK (true);
CREATE POLICY "Public update access for touchpoints" ON touchpoints FOR UPDATE USING (true);


-- Calendar Tiers
CREATE TABLE IF NOT EXISTS calendar_tiers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  color TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

ALTER TABLE calendar_tiers ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read access for calendar_tiers" ON calendar_tiers FOR SELECT USING (true);
CREATE POLICY "Public insert access for calendar_tiers" ON calendar_tiers FOR INSERT WITH CHECK (true);
CREATE POLICY "Public update access for calendar_tiers" ON calendar_tiers FOR UPDATE USING (true);


-- Calendar Events
CREATE TABLE IF NOT EXISTS calendar_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  start_date DATE,
  end_date DATE,
  tier TEXT NOT NULL,
  color TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

ALTER TABLE calendar_events ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read access for calendar_events" ON calendar_events FOR SELECT USING (true);
CREATE POLICY "Public insert access for calendar_events" ON calendar_events FOR INSERT WITH CHECK (true);
CREATE POLICY "Public update access for calendar_events" ON calendar_events FOR UPDATE USING (true);


-- Resources
CREATE TABLE IF NOT EXISTS resources (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  category TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

ALTER TABLE resources ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read access for resources" ON resources FOR SELECT USING (true);
CREATE POLICY "Public insert access for resources" ON resources FOR INSERT WITH CHECK (true);
CREATE POLICY "Public update access for resources" ON resources FOR UPDATE USING (true);


-- Ways of Working (Process)
CREATE TABLE IF NOT EXISTS wow_process (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  sort_order INTEGER,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

ALTER TABLE wow_process ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read access for wow_process" ON wow_process FOR SELECT USING (true);
CREATE POLICY "Public insert access for wow_process" ON wow_process FOR INSERT WITH CHECK (true);
CREATE POLICY "Public update access for wow_process" ON wow_process FOR UPDATE USING (true);


-- Ways of Working (Timeline)
CREATE TABLE IF NOT EXISTS wow_timeline (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  phase TEXT NOT NULL,
  date_text TEXT,
  sort_order INTEGER,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

ALTER TABLE wow_timeline ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read access for wow_timeline" ON wow_timeline FOR SELECT USING (true);
CREATE POLICY "Public insert access for wow_timeline" ON wow_timeline FOR INSERT WITH CHECK (true);
CREATE POLICY "Public update access for wow_timeline" ON wow_timeline FOR UPDATE USING (true);


-- Omnichannel
CREATE TABLE IF NOT EXISTS omnichannel (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  channel TEXT NOT NULL,
  description TEXT,
  content TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

ALTER TABLE omnichannel ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read access for omnichannel" ON omnichannel FOR SELECT USING (true);
CREATE POLICY "Public insert access for omnichannel" ON omnichannel FOR INSERT WITH CHECK (true);
CREATE POLICY "Public update access for omnichannel" ON omnichannel FOR UPDATE USING (true);
