-- Create insight_pages table (plural - supports multiple campaigns)
CREATE TABLE IF NOT EXISTS insight_pages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campaign_id TEXT UNIQUE NOT NULL,
  title TEXT NOT NULL,
  subtitle TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

-- Enable RLS
ALTER TABLE insight_pages ENABLE ROW LEVEL SECURITY;

-- Match existing security pattern (public read/write for admin)
CREATE POLICY "Public read access for insight_pages" ON insight_pages FOR SELECT USING (true);
CREATE POLICY "Public insert access for insight_pages" ON insight_pages FOR INSERT WITH CHECK (true);
CREATE POLICY "Public update access for insight_pages" ON insight_pages FOR UPDATE USING (true);
CREATE POLICY "Public delete access for insight_pages" ON insight_pages FOR DELETE USING (true);

-- Add index for campaign_id lookups
CREATE INDEX IF NOT EXISTS idx_insight_pages_campaign ON insight_pages(campaign_id);

-- Seed current data for campaign-2026
INSERT INTO insight_pages (campaign_id, title, subtitle) VALUES
('campaign-2026', 'Insights & Performance', 'Summer Season Insights.
Data-driven opportunities for the season');
